### PR TITLE
merge 5.0++ and 5.0

### PR DESCRIPTION
**Pull request by FavouriteDragon**

### CODE REVIEW

**Comment by CrowsOfWar** [comment]
If this is about merging, just delete a5.0++ and go back to a5.0 - i already merged the two together (sorta)

**Comment by FavouriteDragon** [comment]
Umm it doesn't have the changes i made in 5.0++: making ability explosion work and creating and status config for the explosion size

**Comment by CrowsOfWar** [comment]
Okay I'll be getting to work on the fix right now, thanks

**Comment by CrowsOfWar** [comment]
Yeah it should be fixed now, sorry. I didn't see your new commits

**Pull request closed without merging**
